### ISSUE TITLE
Snoop bug

### ISSUE THREAD

**Issue by lukefahr** [mbus/m3-python#1]
======================================================
pip install m3_ice + snoop fails
======================================================$ pip install m3_ice
$ m3_ice snoop
INFO	--------------------------------------------------------------------------------
INFO	 -- M3 ICE Interface
INFO
INFO	Guessing ICE is at: /dev/cu.usbserial-A603TU7M
INFO	Connected to serial device at /dev/cu.usbserial-A603TU7M
INFO	This library supports versions...
INFO		0.1
INFO		0.2
INFO		0.3
INFO	This ICE board supports versions...
INFO		0.3 **Chosen version
Traceback (most recent call last):
  File "/usr/local/bin/m3_ice", line 11, in <module>
    sys.exit(cmd())
  File "/usr/local/lib/python2.7/site-packages/m3/m3_ice.py", line 105, in cmd
    m.args.func()
  File "/usr/local/lib/python2.7/site-packages/m3/m3_ice.py", line 91, in cmd_snoop
    snooper = mbus_snooper(self.args, self.ice)
  File "/usr/local/lib/python2.7/site-packages/m3/m3_common.py", line 782, in __init__
    for idx,callback in enumerate(self.args.callback):
TypeError: 'NoneType' object is not iterable

======================================================
building from source works
======================================================
$ git clone https://github.com/mbus/m3-python.git
$ cd m3-python/
$ python setup.py build
$ python setup.py install
$ m3_ice snoop
INFO	--------------------------------------------------------------------------------
INFO	 -- M3 ICE Interface
INFO
INFO	Guessing ICE is at: /dev/cu.usbserial-A603TU7M
INFO	Connected to serial device at /dev/cu.usbserial-A603TU7M
INFO	This library supports versions...
INFO		0.1
INFO		0.2
INFO		0.3
INFO	This ICE board supports versions...
INFO		0.3 **Chosen version
INFO	Script is waiting to print any MBus messages.
INFO	To quit, press Ctrl-C
WARNING	No messages for 10 seconds, resetting ICE

**Comment by ppannuto** [comment]
Pushed updated version 0.5.0 to pypi
